strategy = "trade"
trade_usd = 3
max_retries = 3

[market]
market_coin = "btc"  # btc / eth / sol / xrp
market_period = "5"

[trade]
entry_price_ratio = [0.4, 0.95]
entry_time_ratio = 0.6
exit_price_ratio_range = [[0.0, 0.01], [1.0, 1.0]]
emergency_swap_price = [0.0, 0.5]
